src/models/course_type.py
# -*- coding: utf-8 -*-
from core.db import db
from utils.converter import to_int


class CourseType(db.Model):
    __tablename__ = 'course_type'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(32))

    def __init__(self, name):
        self.name = name

    @classmethod
    def get_all_types(cls):
        return cls.query.all()

    @classmethod
    def find_course_type_by_id(cls, id: int):
        return cls.query.filter_by(id=to_int(id, 'course type id')).first()

src/controllers/course_info.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import session
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from core.lang import get_str
from core.engine import render_context
from core.permission import restricted_access
from core.permission import STUDENT
from core.permission import LECTURER
from core.permission import COURSE_DESIGNER
from utils.converter import to_int
from models.course import Course
from models.report import Report

blueprint = Blueprint('course_info', __name__, template_folder='templates')


@blueprint.route('/course/<int:course_id>', methods=['GET'])
@restricted_access(allowed=[STUDENT, LECTURER, COURSE_DESIGNER])
@render_context('course_info.html', on_error_redirect_to='courses.courses')
def info(course_id):
    course = Course.find_course_by_id(course_id)
    analysis = {}
    if course is None:
        flash(get_str('COURSE_NOT_FOUND'))
        return redirect(url_for('courses.courses'))
    if session['user_type'] == COURSE_DESIGNER or session['user_type'] == LECTURER:
        all_reports = Report.find_reports_by_course_id(course.id)
        years = [report.get_semester().year for report in all_reports]
        # Remove duplicates
        years = list(set(years))
        analysis['years'] = years
        year = to_int(request.args.get('year', -1))
        # Check if it is a valid year (exists for the current course report)
        if year not in years:
            year = years[-1] if len(years) > 0 else -1
        analysis['year_selected'] = year
        if year > 0:
            reports = Report.find_course_reports_by_year(course_id=course.id, year=year)
            if len(reports) > 0:
                # Since there will be at least one report
                course_version = reports[0].get_course_version()
                cilos = course.get_cilos(course_version.id)
                analysis['reports'] = reports
                analysis['cilos'] = cilos
                analysis['scores'] = Report.get_cilo_performance_by_year(course.id, year)
    return {
        'course': course,
        'analysis': analysis
    }

src/controllers/courses.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from core.engine import render_context
from core.lang import get_str
from core.exception import ErrorMessage
from models.course import Course
from models.program import Program
from models.course_type import CourseType
from models.cilo import CILO
from models.assessment_method import AssessmentMethod

blueprint = Blueprint('courses', __name__, template_folder='templates')


@blueprint.route('/courses', methods=['GET', 'POST'])
@render_context('courses.html')
def courses():
    return {
        'courses': Course.find_course_by_keyword(''),
        'programs': Program.get_all_programs(),
        'course_types': CourseType.get_all_types()
    }


@blueprint.route('/courses/add', methods=['POST'])
@render_context('courses.html', commit_on_success=False, rollback_on_exception=False)
def add_course():
    # Deprecated function. Should no longer be used.
    # Moved to APIs
    if request.method == 'POST':
        content = request.get_json()
        Course.add_course(content)
        flash(get_str('CREATED', obj_name=get_str('ACOURSE')))


@blueprint.route('/courses/edit', methods=['POST'])
@render_context('courses.html', commit_on_success=True, rollback_on_exception=True)
def modify_course():
    # Deprecated function. Should no longer be used.
    # Moved to APIs
    if request.method == 'POST':
        content = request.get_json()
        course = Course.find_course_by_id(content['course_id'])
        if course is None:
            raise ErrorMessage(get_str('NOT_FOUND_OBJECT', object_name='course'))
        course.modify_course(content)


@blueprint.route('/courses/', methods=['GET', 'POST'])
def empty_redirect():
    return redirect(url_for('courses.courses'))

src/controllers/dashboard.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import redirect
from flask import url_for
from core.permission import restricted_access
from core.permission import STUDENT
from core.permission import LECTURER
from core.permission import COURSE_DESIGNER

blueprint = Blueprint('dashboard', __name__, template_folder='templates')


@blueprint.route('/', methods=['GET', 'POST'])
@restricted_access(allowed=[STUDENT, LECTURER, COURSE_DESIGNER])
def dashboard():
    return redirect(url_for('courses.courses'))

src/controllers/dependency.py
# -*- coding: utf-8 -*-
from core.exception import ErrorMessage
from flask import request
from flask import Blueprint
from core.engine import render_context
from core.permission import restricted_access
from core.permission import STUDENT
from core.permission import LECTURER
from core.permission import COURSE_DESIGNER
from utils.converter import to_int
from models.degree import Degree

blueprint = Blueprint('dependency', __name__, template_folder='templates')

@blueprint.route('/dependency', methods=['GET'])
@restricted_access(allowed=[STUDENT, LECTURER, COURSE_DESIGNER])
@render_context('dependency.html')
def dependency():
    degrees = Degree.get_all_degrees()
    selected_degree_index = to_int(request.args.get('index', 1), 'index')
    if selected_degree_index < 0 or selected_degree_index > len(degrees):
        selected_degree_index = 0
    return {
        'degrees': degrees,
        'selected_index': selected_degree_index}

src/controllers/login.py
# -*- coding: utf-8 -*-

from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask import get_flashed_messages
from flask import session
from flask_language import current_language

from core.engine import render_context
from core.lang import lang
from core.lang import get_str

from models.user import User

blueprint = Blueprint('login', __name__, template_folder='templates')

@blueprint.route('/login', methods=['GET', 'POST'])
@render_context('login.html')
def login():
    if request.args.get('lang') is not None:
        lang.change_language(request.args.get('lang'))

    if request.method == 'POST':
        user = User.find_user_by_username(request.values.get('username'))
        if user and user.verify_password(request.values.get('password')):
            session['user_id'] = user.get_id()
            session['user_type'] = user.get_user_type()
            session['full_name'] = user.get_full_name()
            return redirect(url_for('dashboard.dashboard'))
        else:
            flash(get_str('INVALID_CREDENTIALS'))


@blueprint.route('/login/', methods=['GET', 'POST'])
def login_redirect():
    return redirect(url_for('login.login'))


@blueprint.route('/logout', methods=['GET'])
def logout():
    session.clear()
    return redirect(url_for('login.login'))

src/controllers/logout.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import session
from flask import redirect
from flask import url_for

blueprint = Blueprint('logout', __name__, template_folder='templates')


@blueprint.route('/logout', methods=['GET'])
def logout():
    session.clear()
    return redirect(url_for('login.login'))

src/controllers/performance_report.py
# -*- coding: utf-8 -*-
from core.exception import ErrorMessage
from operator import index
from flask import Blueprint
from flask import session
from flask import request
from flask import flash
from core.lang import get_str
from core.engine import render_context
from core.permission import restricted_access
from core.permission import STUDENT
from core.permission import LECTURER
from core.permission import COURSE_DESIGNER
from utils.converter import to_int
from models import student_report
from models.course import Course
from models.report import Report
from models.student_report import StudentReport

blueprint = Blueprint('performance_report', __name__, template_folder='templates')


@blueprint.route('/performance', methods=['GET'])
@restricted_access(allowed=[STUDENT])
@render_context('performance_report.html')
def report():
    reports = Report.get_student_completed_courses(session['user_id'])
    completed_courses = [x[0] for x in reports]
    n = len(completed_courses)
    index = to_int(request.args.get('index', 0), 'index')
    cilos = []
    scores = []
    if n > 0:
        if index >= 0 and index < n:
            # Get the index in the student's completed course list
            scores = reports[index][2].get_cilo_performance()
            version = reports[index][1].get_course_version()
            course = reports[index][0]
            cilos = course.get_cilos(course_version_id=version.id)
        else:
            raise ErrorMessage(get_str('INVALID_INDEX'))
    return {
        'completed_courses': completed_courses,
        'index': index,
        'scores': scores,
        'cilos': cilos
    }

src/controllers/search.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import request
from flask import session
from flask import redirect
from flask import flash
from flask.helpers import flash, url_for
from core.lang import get_str
from core.exception import ErrorMessage
from core.engine import render_context
from core.permission import restricted_access
from core.permission import STUDENT
from core.permission import LECTURER
from core.permission import COURSE_DESIGNER
from models.course import Course
from models.cilo import CILO

blueprint = Blueprint('search', __name__, template_folder='templates')


@blueprint.route('/search', methods=['GET', 'POST'])
@restricted_access(allowed=[STUDENT, LECTURER, COURSE_DESIGNER])
@render_context('search.html')
def search():
    pass


@blueprint.route('/search/result', methods=['GET', 'POST'])
@restricted_access(allowed=[STUDENT, LECTURER, COURSE_DESIGNER])
@render_context('search_results.html')
def search_result():
    search_type = request.args.get('type', None)
    search_keyword = request.args.get('keyword', None)

    if search_type is None:
        raise ErrorMessage(get_str('SEARCH_TYPE_EMPTY'))
    if search_keyword is None:
        raise ErrorMessage(get_str('SEARCH_KEYWORD_EMPTY'))

    if search_type == 'course':
        return {
            'courses': Course.find_course_by_keyword(search_keyword), 
            'search_type': search_type}
    elif search_type == 'cilo':
        cilos = CILO.find_cilo_by_keyword(search_keyword)
        courses = []
        for cilo in cilos:
            courses.append(Course.find_course_by_id(cilo.course_id))
        return {
            'cilos': cilos, 
            'courses': courses, 
            'search_type': search_type}
    elif search_type == 'keyword':
        results = Course.find_courses_cilo_by_keyword(keyword=search_keyword)
        courses = [result[0] for result in results]
        cilos = [result[1] for result in results]
        return {
            'cilos': cilos, 
            'courses': courses, 
            'search_type': search_type}
    else:
        flash(get_str('INVALID_SEARCH_TYPE'))
        return redirect(url_for('search.search'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<head>
	<meta charset="utf-8">
	<!-- Mobile Compatibility -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	<!-- Bootstrap -->
	<link rel="stylesheet" href="/static/bootstrap-4.6.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.min.css">
	<title>{% block title %}{% endblock %} - DegreeOverview</title>
	<!-- Custom CSS -->
	<link rel="stylesheet" href="/static/css/base.css">
	{% block custom_style %}{% endblock %}
	{% block header_script %}{% endblock %}
</head>

<body>
	{% macro input() -%}
	<a href="{{ url_for('courses.courses') }}" class="list-group-item list-group-item-action bg-light">{{
		get_str('COURSES') }}</a>
	{% if session['user_type'] == STUDENT %}
	<a href="{{ url_for('performance_report.report') }}" class="list-group-item list-group-item-action bg-light">{{
		get_str('PERFORMANCE_REPORT') }}</a>
	{% endif %}
	<a href="{{ url_for('search.search') }}" class="list-group-item list-group-item-action bg-light">{{
		get_str('SEARCH') }}</a>
	<a href="{{ url_for('dependency.dependency') }}" class="list-group-item list-group-item-action bg-light">{{
		get_str('OUTCOME_DEPENDENCY') }}</a>
	{%- endmacro %}
	<div class="d-flex" id="wrapper">

		<!-- Sidebar -->
		<div class="bg-light border-right" id="sidebar-wrapper">
			<div class="sidebar-heading">
				<a href="{{ url_for('dashboard.dashboard') }}">
					<img src="/static/logo_horizontal.png" alt="Logo" width="175">
			</div>
			</a>
			<div class="list-group list-group-flush">
				{{ input() }}

			</div>
		</div>
		<!-- sidebar-wrapper -->

		<!-- Page Content -->
		<div id="page-content-wrapper">

			<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
				<button class="btn btn-light" id="menu-toggle">{{ get_str('MENU') }}</button>

				<button class="navbar-toggler" type="button" data-toggle="collapse"
					data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
					aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-user-circle-o"></i> {{ session['full_name'] }}</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{{ url_for('logout.logout') }}">{{ get_str('LOGOUT')
									}}</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<div class="container-fluid">
				{% block content %}

				{% endblock %}
			</div>
			{% block dependency %}

			{% endblock %}
		</div>
		<!-- page-content-wrapper -->

	</div>
	<!-- wrapper -->

	<!-- Bootstrap core JavaScript -->
	<!-- jQuery -->
	<script src="/static/js/jquery-3.5.1.min.js"></script>
	<!-- Bootstrap Related -->
	<script src="/static/js/popper.min.js"></script>
	<script src="/static/bootstrap-4.6.0/js/bootstrap.min.js"></script>
	{% block script %}

	{% endblock %}

	<!-- Modal for message -->
	<div class="modal fade dialog-modal" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel"
		data-backdrop="static" data-keyboard="false" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">{{ get_str('MESSAGE') }}</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					{% with messages = get_flashed_messages() %}
					{% if messages %}
					{% for message in messages %}
					<p id="returned-message">{{ message }}</p>
					{% endfor %}
					{% endif %}
					{% endwith %}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal" id="dialog-comfirm-button">{{
						get_str('CONFIRM') }}</button>
				</div>
			</div>
		</div>
	</div>

	<!-- Message Modal Script -->
	<script type="text/javascript">
		// Message Modal Script
		if ($('#returned-message').text().length > 0) {
			$('#messageModal').modal('show')
		}
		// Menu Toggle Script
		$("#menu-toggle").click(function (e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled")
		})
		// Tooltip for changing password
		$('#password-new-password').tooltip({ 'trigger': 'focus', 'title': 'The password should be 8-24 characters long, containing upper and lower case letters, and digits.' })
		$('.dialog-modal').on('hidden.bs.modal', function (event) {
			$("body").addClass("modal-open");
		})
	</script>
</body>

</html>

src/templates/course_info.html
{% extends "base.html" %}
{% macro tag_title() -%}
{% if session['user_type'] == STUDENT %}
{{ get_str('STUDENT') }}
{% elif session['user_type'] == LECTURER %}
{{ get_str('LECTURER') }}
{% elif session['user_type'] == COURSE_DESIGNER %}
{{ get_str('COURSE_DESIGNER') }}
{% endif %}
{%- endmacro %}
{% block title %} {{ tag_title() }} {% endblock%}

{% block content %}

{% macro tab_title() -%}
{{ get_str('COURSES_INFO') }}
{%- endmacro %}

{% block custom_style %}
<style>
	.dropdown-menu::-webkit-scrollbar {
		display: none;
	}
</style>
{% endblock %}

<div class="row">
	<div class="col" id="location">
		<span>
			<p style="font-weight:bold">{{ tab_title() }}</p>
		</span>
	</div>
</div>
  <!--course info-->
  <div class="row text-center" style="margin-left: 5%; margin-right: 10%">
    <h5 class="col">{{ get_str('BASICINFO') }}</h5>
  </div>
  <br>
  <div class="row align-items-start" style="margin-bottom: 1%; margin-left: 5%">
    <div class="col-6"><p>{{ get_str('COURSE_TITLE') }}: {{ data['course'].course_name }}</p></div>
    <div class="col-6"><p>{{ get_str('COURSE_CODE') }}: {{ data['course'].course_code }}</p></div>
    <div class="w-100"></div>
    <div class="col-6"><p>{{ get_str('COURSE_TYPE') }}: {{ data['course'].get_couse_type().name }}</p></div>
    <div class="col-6"><p>{{ get_str('PROGRAM') }}: {{ data['course'].get_program().name }}</p></div>
    <div class="w-100"></div>
    <div class="col-12">
      <p>{{ get_str('PRECOURSES') }}: 
        {% set courses = data['course'].get_course_prerequisites() %}
        {% if len(courses) == 0 %}
          None
        {% else %}
          {% for idx, course in enumerate(courses) %}{% if idx != 0 %}, {% endif %}{{ course[0].course_name }}{% endfor %}</p>
        {% endif %}
    </div>
    <div class="col-12">
      <p>{{ get_str('POSTCOURSES') }}: 
        {% set courses = data['course'].get_dependent_courses() %}
        {% if len(courses) == 0 %}
          None</p>
        {% else %}
          <ul>
          {% for course in courses %}
            <li>{{ course[0].course_name }}</li>
          {% endfor %}</ul>
        {% endif %}
    </div>  
  </div>
  <div class="row align-items-center" style="margin-top: 2%; margin-left: 4%; margin-right: 4%">
    <div class="col-sm-12">
      <table class="table table-bordered table-striped table-hover">
        <thead class="text-center">
          <tr>
            <th colspan=2>{{ get_str('CILOS') }}</th>
          </tr>
          <tr>
            <th>{{ get_str('NAME') }}</th>
            <th>{{ get_str('DESCRIPTION') }}</th>
          </tr>
        </thead>
        {% for cilo in data['course'].get_cilos() %}
        <tr>
          <td>CILO {{ cilo.cilo_index }}</td>
          <td>{{ cilo.cilo_description }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <div class="row align-items-center" style="margin-top: 2%; margin-left: 4%; margin-right: 4%">
    <div class="col-sm-12">
      <table class="table table-bordered table-striped table-hover">
        <thead class="text-center">
          <tr>
            <th colspan=3>{{ get_str('ASSESSMENT_METHODS') }}</th>
          </tr>
          <tr>
            <th>{{ get_str('NAME') }}</th>
            <th>{{ get_str('WEIGHTING') }}</th>
            <th>{{ get_str('CILOS_ADDRESSED') }}</th>
          </tr>
        </thead>
        {% for assessment_method in data['course'].get_assessment_methods() %}
        <tr>
          <td>{{ assessment_method.method_name }}</td>
          <td>{{ assessment_method.weight }}%</td>
          <td>
            {% for idx, cilo in enumerate(assessment_method.get_cilos_addressed()) %}{% if idx >= 1 %}, {% endif %}{{ cilo.cilo_index }}{% endfor %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  {% if session['user_type'] != STUDENT %}
  <!--Analysis Results-->
  <br>
  <div class="row no-gutters" style="margin-left: 5%; margin-right: 5%">
      <div class="col-sm-9" style="margin-left: 12%">
        <h5 class="text-center">{{ get_str('ANALYSIS') }}</h5>
      </div>
      <div class="col" style="text-align: right;">
        <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          {{ str(str(data['analysis']['year_selected']) + "-" + str(data['analysis']['year_selected']+1)) if data['analysis']['year_selected'] > 0 else get_str('NO_REPORT') }}
        </button>
        <div class="dropdown-menu text-right" aria-labelledby="dropdownMenuButton" style="min-width: 0;">
          {% for year in data['analysis']['years'] %}
            <a class="dropdown-item" href="{{ url_for('course_info.info', course_id=data['course'].id) }}?year={{year}}">
              {{ year }}-{{ year+1 }}
            </a>
          {% endfor %}
        </div>
      </div>
      <div class="col-sm-12">
        <br>
      <table class="table table-bordered table-striped table-hover">
        <thead class="text-center">
          <tr>
            <th>{{ get_str('NAME') }}</th>
            <th>{{ get_str('CILO_DESCRIPTION') }}</th>
            <th>{{ get_str('PERCENTAGE') }}</th>
          </tr>
        </thead>
        <tbody>
          {% for idx, cilo in enumerate(data['analysis']['cilos']) %}
          <tr>
            <td>CILO {{ cilo.cilo_index }}</td>
            <td>{{ cilo.cilo_description }}</td>
            <td>{{ "{:5.2f}".format(data['analysis']['scores'][idx] * 100) }}%</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}


  {% endblock %}

src/templates/performance_report.html
{% extends "base.html" %}
{% macro tag_title() -%}
{% if session['user_type'] == STUDENT %}
{{ get_str('STUDENT') }}
{% elif session['user_type'] == LECTURER %}
{{ get_str('LECTURER') }}
{% elif session['user_type'] == COURSE_DESIGNER %}
{{ get_str('COURSE_DESIGNER') }}
{% endif %}
{%- endmacro %}
{% block title %} {{ tag_title() }} {% endblock%}

{% block content %}

{% macro tab_title() -%}
{{ get_str('PERFORMANCE') }}
{%- endmacro %}

{% block custom_style %}
<style>
  .dropdown-menu::-webkit-scrollbar {
    display: none;
  }
</style>
{% endblock %}

<div class="row">
  <div class="col" id="location">
    <span>
      <p style="font-weight:bold">{{ tab_title() }}</p>
    </span>
  </div>
</div>

{% if len(data['completed_courses']) == 0 %}

<div>
  <p style="text-align: center;">No reports available.</p>
</div>

{% else %}
<div class="row no-gutters text-right">
  <div class="col">
    <button class="btn btn-outline-link btn dropdown-toggle" type="button" id="dropdownMenuButton"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {% if len(data['completed_courses']) > 0 %}{{ data['completed_courses'][data['index']].course_name }}{% endif %}
    </button>
    <div class="dropdown-menu text-right" aria-labelledby="dropdownMenuButton">
      {% for idx, course in enumerate(data['completed_courses']) %}
      <a class="dropdown-item" href="{{ url_for('performance_report.report') }}?index={{ idx }}">{{ course.course_name
        }}</a>
      {% endfor %}
    </div>
  </div>
</div>
<div class="row no-gutters">
  <div class="col">
    <table class="table table-bordered table-striped table-hover">
      <tbody>
        <tr>
          <th>CILO</th>
          <th>{{ get_str('CILO_DESCRIPTION') }}</th>
          <th>{{ get_str('PERFORMANCE') }}</th>
        </tr>
        {% for idx, cilo in enumerate(data['cilos']) %}
        <tr>
          <td>CILO {{ cilo.cilo_index }}</td>
          <td>{{ cilo.cilo_description }}</td>
          <td>{{ "{:5.2f}".format(data['scores'][idx] * 100) }}%</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endif %}

{% endblock %}

src/templates/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block base_css %}
	<link rel="stylesheet" href="/static/css/base.css">
{% endblock %}

{% block content %}
<div class="container text-center">
  <form class="search" method="post">
    <br>
    <img class="mb-4" src="/static/logo_horizontal.png" alt="" width=360>
    <h1 class="h3 mb-3 font-weight-normal">{{ get_str('SEARCH') }}</h1>
    <br><br>
    <form class="bs-example bs-example-form" role="form">
      <div class="row justify-content-center">
        <div class="col-11 align-self-center">
          <div class="input-group">
            <div class="input-group-btn">
              <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                {{ get_str('KEYWORDS') }}
              </button>
              <ul class="dropdown-menu" style="margin-top: -1px">
                <li>
                  <a class="dropdown-item" href="#" id="type_keywords" onclick="search_type_select(this)" data-type="keyword">{{ get_str('KEYWORDS') }}</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#" id="type_course" onclick="search_type_select(this)" data-type="course">{{ get_str('COURSES') }}</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#" id="type_CILO" onclick="search_type_select(this)" data-type="cilo">{{ get_str('CILOS') }}</a>
                </li>
              </ul>
            </div>
            <label for="Search" class="sr-only">{{ get_str('SEARCH') }}</label>
            <input type="text" name="search" class="form-control" placeholder="{{ get_str('SEARCH') }}" required=""
              autofocus="" id="searchKeywords">
            <div>
              <button class="btn btn-light" type="button" name="submit" id="searchBtn"><a href="#">{{ get_str('SEARCH') }}</a></button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </form>
</div>

{% endblock %}

{% block script %}
<script>
  // TODO: add form to search button to change search type
  var searchType = 'keyword';

  $("#searchBtn").on("click", search);

  function search() {
    window.location.href = '{{ url_for("search.search_result") }}?type=' 
      + searchType + '&keyword=' + encodeURI($('#searchKeywords').val());
  }

  $('#searchKeywords').keypress(function(event) {
    var keycode = (event.keyCode ? event.keyCode : event.which);
    // When entered pressed
    if(keycode == '13') {
      event.preventDefault();
      search();
    }
  });

  function search_type_select(obj) {
    var e = obj
    var text = $(obj).text();
    searchType = $(obj).attr('data-type');
    console.log(searchType);
    $("#dropdownMenuButton").text(text);
  }
</script>
{% endblock %}